### ISSUE TITLE
dedot_lv0* tests fail

### ISSUE THREAD

**Issue by ignatenkobrain** [magiclen/path-dedot#3]
```rust
---- dedot_lv0_2 stdout ----
thread 'dedot_lv0_2' panicked at 'called `Option::unwrap()` on a `None` value', tests/unix.rs:32:17

---- dedot_lv0_1 stdout ----
thread 'dedot_lv0_1' panicked at 'called `Option::unwrap()` on a `None` value', tests/unix.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    dedot_lv0_1
    dedot_lv0_2
```

let me know what other information you need to know.

**Comment by ignatenkobrain** [comment]
seems that running with `--test-threads=1` fixes the issue.

**Comment by magiclen** [comment]
Thank you. It's been fixed.

**Comment by ignatenkobrain** [comment]
Thank you!
